mytest:mytest.c
	gcc -o $@ $^ -I./lib -L./lib -lmymath  # 这里只是告知编译器头文件库在那里，当程序编好了，就与编译无关了
.PHONY:clean
clean:
	rm -f mytest









# mytest:mytest.c
# 	gcc -o $@ $^ -I./lib -L./lib -lmymath
# .PHONY:clean
# clean:
# 	rm -f mytest